In [234]:
import numpy as np
import random
import pandas as pd

In [235]:
def generate_interest(num):
    # create a list of user ids
    user_ids = list(range(1, num+1))

    # create a dictionary to hold binary data for each variable
    data_dict = {}
    for i in range(7):
        data_dict[f"interest_{i+1}"] = np.random.randint(0, 2, num)

    # create a dataframe from the user ids and binary data dictionary
    df = pd.DataFrame({"id": user_ids, **data_dict})
    return df

def cosine_similarity(user, mentor):
    vec1 = user
    vec2 = mentor
    cosine = np.dot(vec1,vec2)/((np.dot(vec1,vec1)*np.dot(vec2,vec2))**0.5) 
    return cosine

In [236]:
# set the number of users
num_users = 100
num_mentor = 5

df_user = generate_interest(num_users)
df_mentor = generate_interest(num_mentor)

In [237]:
df_user

,id,interest_1,interest_2,interest_3,interest_4,interest_5,interest_6,interest_7
0,1,1,1,1,1,0,0,0
1,2,0,0,1,1,0,1,0
2,3,1,1,1,1,1,1,0
3,4,0,1,1,0,0,1,0
4,5,0,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...
95,96,1,0,0,1,1,0,1
96,97,1,1,1,1,1,0,0
97,98,1,1,0,0,0,0,1
98,99,0,0,1,0,0,0,0
99,100,0,1,0,0,0,0,0

In [238]:
df_mentor

,id,interest_1,interest_2,interest_3,interest_4,interest_5,interest_6,interest_7
0,1,0,0,0,1,1,1,0
1,2,1,1,1,1,1,1,0
2,3,1,0,1,1,0,1,1
3,4,1,1,0,1,0,1,0
4,5,0,0,0,1,0,0,0

In [239]:
df_mentor.iloc[1,1:].values

array([1, 1, 1, 1, 1, 1, 0])

In [240]:
menteeId = [i for i in df_user.id]
mentorId = [i for i in df_mentor.id]

In [241]:
mentee2mentor = {}
sim_mentee={}
con = []
var = [f"interest_{i+1}" for i in range(7)]
for u in menteeId:
    mentee2mentor[u] = mentorId
    user = df_user.loc[df_user.id==u,var].values.reshape(1,-1)
    user = np.squeeze(np.asarray(user))
    print(f'user {u}',user)
    for m in mentorId:
        mentor = df_mentor.loc[df_mentor.id==m,var].values.reshape(1,-1)
        mentor = np.squeeze(np.asarray(mentor))
        print(f'mentor {m}',mentor)
        sim = cosine_similarity(user, mentor)
        con.append(np.abs(sim))
    sim_mentee[u] = con
    con = []

user 1 [1 1 1 1 0 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 2 [0 0 1 1 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 3 [1 1 1 1 1 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 4 [0 1 1 0 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 5 [0 0 1 1 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 6 [0 0 0 1 1 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 7 [1 0 0 0 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 8 [0 1 1 1 1 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 9 [0 0 0 1 0 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 10 [0 1 1 0 1 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 11 [1 0 0 1 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 12 [1 0 1 0 1 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 13 [1 0 0 1 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 14 [1 1 0 0 1 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 15 [1 0 0 0 1 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 16 [1 0 1 1 0 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 17 [1 0 1 0 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 18 [1 0 1 0 0 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 19 [1 1 1 1 0 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 20 [1 1 0 0 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 21 [0 1 0 0 0 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 22 [0 0 0 1 0 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 23 [1 1 0 0 0 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 24 [0 1 1 1 1 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 25 [0 1 0 0 0 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 26 [0 1 1 0 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 27 [1 0 0 0 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 28 [1 1 1 0 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 29 [0 1 0 0 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 30 [1 1 1 0 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 31 [0 0 0 1 0 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 32 [1 1 0 1 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 33 [1 0 1 0 1 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 34 [0 0 1 0 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 35 [1 0 1 0 0 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 36 [0 0 0 0 1 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 37 [0 0 0 0 1 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 38 [0 1 1 1 0 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 39 [0 0 0 0 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 40 [0 1 0 1 0 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 41 [0 1 1 1 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 42 [1 1 1 1 1 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 43 [1 0 1 1 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 44 [1 0 0 1 0 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 45 [0 0 1 1 1 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 46 [1 1 1 1 1 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 47 [0 1 0 1 0 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 48 [0 1 0 0 0 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 49 [1 0 1 0 0 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 50 [0 0 1 1 1 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 51 [0 0 0 1 0 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 52 [1 0 0 1 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 53 [0 1 0 1 0 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 54 [0 1 1 0 1 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 55 [1 1 1 1 0 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 56 [0 0 0 1 1 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 57 [0 1 0 1 0 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 58 [1 1 1 0 1 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 59 [1 0 1 0 0 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 60 [0 1 1 1 0 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 61 [1 0 0 1 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 62 [1 1 1 0 1 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 63 [1 1 1 0 1 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 64 [0 0 0 1 0 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 65 [1 0 1 1 0 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 66 [1 1 1 1 1 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 67 [0 1 1 0 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 68 [0 0 0 0 0 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 69 [1 0 1 1 1 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 70 [0 1 0 0 0 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 71 [0 1 0 0 1 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 72 [1 1 1 1 0 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 73 [1 0 0 0 1 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 74 [0 1 1 0 1 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 75 [0 1 1 1 1 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 76 [1 1 1 1 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 77 [1 1 0 0 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 78 [1 0 0 0 0 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 79 [0 1 1 1 0 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 80 [1 0 1 1 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 81 [0 0 0 0 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 82 [0 0 0 0 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 83 [1 0 1 1 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 84 [0 1 1 1 1 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 85 [0 0 1 1 0 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 86 [1 1 0 1 1 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 87 [1 0 0 0 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 88 [1 0 0 0 0 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 89 [0 1 0 0 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 90 [1 1 1 0 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 91 [0 0 1 1 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 92 [0 1 0 1 1 1 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 93 [1 0 1 0 1 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 94 [0 1 0 0 0 1 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 95 [1 0 1 0 1 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 96 [1 0 0 1 1 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 97 [1 1 1 1 1 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 98 [1 1 0 0 0 0 1]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 99 [0 0 1 0 0 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]
user 100 [0 1 0 0 0 0 0]
mentor 1 [0 0 0 1 1 1 0]
mentor 2 [1 1 1 1 1 1 0]
mentor 3 [1 0 1 1 0 1 1]
mentor 4 [1 1 0 1 0 1 0]
mentor 5 [0 0 0 1 0 0 0]

In [242]:
mentee2mentor

{1: [1, 2, 3, 4, 5],
 2: [1, 2, 3, 4, 5],
 3: [1, 2, 3, 4, 5],
 4: [1, 2, 3, 4, 5],
 5: [1, 2, 3, 4, 5],
 6: [1, 2, 3, 4, 5],
 7: [1, 2, 3, 4, 5],
 8: [1, 2, 3, 4, 5],
 9: [1, 2, 3, 4, 5],
 10: [1, 2, 3, 4, 5],
 11: [1, 2, 3, 4, 5],
 12: [1, 2, 3, 4, 5],
 13: [1, 2, 3, 4, 5],
 14: [1, 2, 3, 4, 5],
 15: [1, 2, 3, 4, 5],
 16: [1, 2, 3, 4, 5],
 17: [1, 2, 3, 4, 5],
 18: [1, 2, 3, 4, 5],
 19: [1, 2, 3, 4, 5],
 20: [1, 2, 3, 4, 5],
 21: [1, 2, 3, 4, 5],
 22: [1, 2, 3, 4, 5],
 23: [1, 2, 3, 4, 5],
 24: [1, 2, 3, 4, 5],
 25: [1, 2, 3, 4, 5],
 26: [1, 2, 3, 4, 5],
 27: [1, 2, 3, 4, 5],
 28: [1, 2, 3, 4, 5],
 29: [1, 2, 3, 4, 5],
 30: [1, 2, 3, 4, 5],
 31: [1, 2, 3, 4, 5],
 32: [1, 2, 3, 4, 5],
 33: [1, 2, 3, 4, 5],
 34: [1, 2, 3, 4, 5],
 35: [1, 2, 3, 4, 5],
 36: [1, 2, 3, 4, 5],
 37: [1, 2, 3, 4, 5],
 38: [1, 2, 3, 4, 5],
 39: [1, 2, 3, 4, 5],
 40: [1, 2, 3, 4, 5],
 41: [1, 2, 3, 4, 5],
 42: [1, 2, 3, 4, 5],
 43: [1, 2, 3, 4, 5],
 44: [1, 2, 3, 4, 5],
 45: [1, 2, 3, 4, 5],
 46: [1, 2, 3, 4, 5],
 47: [1, 2, 3, 4, 5],
 48: [1, 2, 3, 4, 5],
 49: [1, 2, 3, 4, 5],
 50: [1, 2, 3, 4, 5],
 51: [1, 2, 3, 4, 5],
 52: [1, 2, 3, 4, 5],
 53: [1, 2, 3, 4, 5],
 54: [1, 2, 3, 4, 5],
 55: [1, 2, 3, 4, 5],
 56: [1, 2, 3, 4, 5],
 57: [1, 2, 3, 4, 5],
 58: [1, 2, 3, 4, 5],
 59: [1, 2, 3, 4, 5],
 60: [1, 2, 3, 4, 5],
 61: [1, 2, 3, 4, 5],
 62: [1, 2, 3, 4, 5],
 63: [1, 2, 3, 4, 5],
 64: [1, 2, 3, 4, 5],
 65: [1, 2, 3, 4, 5],
 66: [1, 2, 3, 4, 5],
 67: [1, 2, 3, 4, 5],
 68: [1, 2, 3, 4, 5],
 69: [1, 2, 3, 4, 5],
 70: [1, 2, 3, 4, 5],
 71: [1, 2, 3, 4, 5],
 72: [1, 2, 3, 4, 5],
 73: [1, 2, 3, 4, 5],
 74: [1, 2, 3, 4, 5],
 75: [1, 2, 3, 4, 5],
 76: [1, 2, 3, 4, 5],
 77: [1, 2, 3, 4, 5],
 78: [1, 2, 3, 4, 5],
 79: [1, 2, 3, 4, 5],
 80: [1, 2, 3, 4, 5],
 81: [1, 2, 3, 4, 5],
 82: [1, 2, 3, 4, 5],
 83: [1, 2, 3, 4, 5],
 84: [1, 2, 3, 4, 5],
 85: [1, 2, 3, 4, 5],
 86: [1, 2, 3, 4, 5],
 87: [1, 2, 3, 4, 5],
 88: [1, 2, 3, 4, 5],
 89: [1, 2, 3, 4, 5],
 90: [1, 2, 3, 4, 5],
 91: [1, 2, 3, 4, 5],
 92: [1, 2, 3, 4, 5],
 93: [1, 2, 3, 4, 5],
 94: [1, 2, 3, 4, 5],
 95: [1, 2, 3, 4, 5],
 96: [1, 2, 3, 4, 5],
 97: [1, 2, 3, 4, 5],
 98: [1, 2, 3, 4, 5],
 99: [1, 2, 3, 4, 5],
 100: [1, 2, 3, 4, 5]}

In [243]:
mentee2mentor
df = pd.DataFrame([(k, v) for k, values in mentee2mentor.items() for v in values], columns=['user_id', 'mentor_id'])

In [244]:
sim_mentee[1][1]

0.8164965809277261

In [245]:
df['similarity'] = df['user_id'].copy()

In [246]:
for row in range(df.shape[0]):
    #print(row)
    user = df.iloc[row,0]
    mentor = df.iloc[row,1]
    print(user,mentor)
    df['similarity'][row] = sim_mentee[user][mentor-1]

1 1
1 2
1 3
1 4
1 5
2 1
2 2
2 3
2 4
2 5
3 1
3 2
3 3
3 4
3 5
4 1
4 2
4 3
4 4
4 5
5 1
5 2
5 3
5 4
5 5
6 1
6 2
6 3
6 4
6 5
7 1
7 2
7 3
7 4
7 5
8 1
8 2
8 3
8 4
8 5
9 1
9 2
9 3
9 4
9 5
10 1
10 2
10 3
10 4
10 5
11 1
11 2
11 3
11 4
11 5
12 1
12 2
12 3
12 4
12 5
13 1
13 2
13 3
13 4
13 5
14 1
14 2
14 3
14 4
14 5
15 1
15 2
15 3
15 4
15 5
16 1
16 2
16 3
16 4
16 5
17 1
17 2
17 3
17 4
17 5
18 1
18 2
18 3
18 4
18 5
19 1
19 2
19 3
19 4
19 5
20 1
20 2
20 3
20 4
20 5
21 1
21 2
21 3
21 4
21 5
22 1
22 2
22 3
22 4
22 5
23 1
23 2
23 3
23 4
23 5
24 1
24 2
24 3
24 4
24 5
25 1
25 2
25 3
25 4
25 5
26 1
26 2
26 3
26 4
26 5
27 1
27 2
27 3
27 4
27 5
28 1
28 2
28 3
28 4
28 5
29 1
29 2
29 3
29 4
29 5
30 1
30 2
30 3
30 4
30 5
31 1
31 2
31 3
31 4
31 5
32 1
32 2
32 3
32 4
32 5
33 1
33 2
33 3
33 4
33 5
34 1
34 2
34 3
34 4
34 5
35 1
35 2
35 3
35 4
35 5
36 1
36 2
36 3
36 4
36 5
37 1
37 2
37 3
37 4
37 5
38 1
38 2
38 3
38 4
38 5
39 1
39 2
39 3
39 4
39 5
40 1
40 2
40 3
40 4
40 5
41 1
41 2
41 3
41 4
41 5
42 1
42 2
42 3
42 4
42 5
43 1
43 2
43 3
43 4
43 5
44 1
44 2
44 3
44 4
44 5
45 1
45 2
45 3
45 4
45 5
46 1
46 2
46 3
46 4
46 5
47 1
47 2
47 3
47 4
47 5
48 1
48 2
48 3
48 4
48 5
49 1
49 2
49 3
49 4
49 5
50 1
50 2
50 3
50 4
50 5
51 1
51 2
51 3
51 4
51 5
52 1
52 2
52 3
52 4
52 5
53 1
53 2
53 3
53 4
53 5
54 1
54 2
54 3
54 4
54 5
55 1
55 2
55 3
55 4
55 5
56 1
56 2
56 3
56 4
56 5
57 1
57 2
57 3
57 4
57 5
58 1
58 2
58 3
58 4
58 5
59 1
59 2
59 3
59 4
59 5
60 1
60 2
60 3
60 4
60 5
61 1
61 2
61 3
61 4
61 5
62 1
62 2
62 3
62 4
62 5
63 1
63 2
63 3
63 4
63 5
64 1
64 2
64 3
64 4
64 5
65 1
65 2
65 3
65 4
65 5
66 1
66 2
66 3
66 4
66 5
67 1
67 2
67 3
67 4
67 5
68 1
68 2
68 3
68 4
68 5
69 1
69 2
69 3
69 4
69 5
70 1
70 2
70 3
70 4
70 5
71 1
71 2
71 3
71 4
71 5
72 1
72 2
72 3
72 4
72 5
73 1
73 2
73 3
73 4
73 5
74 1
74 2
74 3
74 4
74 5
75 1
75 2
75 3
75 4
75 5
76 1
76 2
76 3
76 4
76 5
77 1
77 2
77 3
77 4
77 5
78 1
78 2
78 3
78 4
78 5
79 1
79 2
79 3
79 4
79 5
80 1
80 2
80 3
80 4
80 5
81 1
81 2
81 3
81 4
81 5
82 1
82 2
82 3
82 4
82 5
83 1
83 2
83 3
83 4
83 5
84 1
84 2
84 3
84 4
84 5
85 1
85 2
85 3
85 4
85 5
86 1
86 2
86 3
86 4
86 5
87 1
87 2
87 3
87 4
87 5
88 1
88 2
88 3
88 4
88 5
89 1
89 2
89 3
89 4
89 5
90 1
90 2
90 3
90 4
90 5
91 1
91 2
91 3
91 4
91 5
92 1
92 2
92 3
92 4
92 5
93 1
93 2
93 3
93 4
93 5
94 1
94 2
94 3
94 4
94 5
95 1
95 2
95 3
95 4
95 5
96 1
96 2
96 3
96 4
96 5
97 1
97 2
97 3
97 4
97 5
98 1
98 2
98 3
98 4
98 5
99 1
99 2
99 3
99 4
99 5
100 1
100 2
100 3
100 4
100 5

In [247]:
df_sorted_rating = df.sort_values(by=['user_id','similarity'],ascending=[True,False]).copy()
df_sorted_rating

     user_id  mentor_id  similarity
1          1          2    0.816497
3          1          4    0.750000
2          1          3    0.670820
4          1          5    0.500000
0          1          1    0.288675
..       ...        ...         ...
498      100          4    0.500000
496      100          2    0.408248
495      100          1    0.000000
497      100          3    0.000000
499      100          5    0.000000

[500 rows x 3 columns]

In [249]:
userSearch = 1
list_mentor_time = [2,3,4] ### time availability
df_sorted_rating[df_sorted_rating.user_id==userSearch & df_sorted_rating.mentor_id.isin(list_mentor_time)]

   user_id  mentor_id  similarity
1        1          2    0.816497
3        1          4    0.750000
2        1          3    0.670820